### PR TITLE
Update Scala & SBT versions, etc.

### PR DESCRIPTION
**Pull request by ches**
I'm trying to get back to finishing a couple of WIP branches I left off on a year ago… These were little updates I wanted to get out of the way so I could rebase over them.

### CODE REVIEW

**Comment by gorzell** [comment]
:+1:

**Comment by gorzell** [comment]
I'd like to merge this after the other open PR.

**Comment by ches** [comment]
Sounds good to me!

**Comment by ches** [comment]
Rebased after the merge of #38.

**Comment by terryhorner** [comment]
:+1:

**Comment by ches** [comment]
Anything that this is waiting on now?

**Pull request merged**
