### PR TITLE
Code quality: fix lint warnings and enforce formatting style

### PR DESCRIPTION
**Pull request by ches**
I noticed a bunch of inconsistent code formatting after recent changes, so I added the [Scalariform SBT plugin][1] to automatically format code upon `sbt compile`. I took the liberty of setting a few preferences that I happen to like (which incidentally are the same as [the sbt-scalariform projects's own settings][2]), but I don't particularly care what the settings are, I'd just like what is expected in code reviews to be unambiguous so it isn't a distraction. You can [peruse the available preference settings][3] in case you wish to suggest something different.

This also turns on the `-Xlint` compiler option and fixes a few complaints it raised. See `scalac -Xlint:help` for a summary of common pitfalls it helps to catch.

For now this is passively enforced, I didn't want to get too opinionated without consensus. We could add `-Xfatal-warnings` to the `scalacOptions` to cause lint warnings to fail CI builds. `sbt-scalariform` doesn't expose a similar feature, yet, but [there is talk of it][4].

There is also [Scalastyle][5] which somewhat confusingly mixes source code formatting checks and other static analysis checks. It doesn't actually *apply* source formatting AFAICT, and has a bunch of (XML) configuration that might be contentious to bikeshed over, so I didn't go so far as adding it here, yet. It might be worth discussing though, since it does offer a few useful code quality checks (for an open source library, I particularly like the check for missing ScalaDoc). It does have a setting to fail SBT builds.

[1]: https://github.com/sbt/sbt-scalariform
[2]: https://github.com/sbt/sbt-scalariform/blob/61a0b7b75441b458e4ff3c6c30ed87d087a2e569/scalariform.sbt
[3]: http://scala-ide.org/scalariform/#preferences
[4]: https://github.com/sbt/sbt-scalariform/issues/35
[5]: http://www.scalastyle.org/

### CODE REVIEW

**Comment by ches** [comment]
[Scapegoat](https://github.com/sksamuel/scapegoat) could also be a worthy alternative to Scalastyle.

**Comment by terryhorner** [comment]
We use Scalastyle internally so using it here would make sense too.

**Comment by ches** [comment]
Can adding Scalastyle be proposed separately, then? It's pretty much orthogonal to my main interest here—automated formatting—if it's only capable of reporting formatting discrepancies instead of fixing them. Linting is secondary to me for now, turning on `-Xlint` was just a bonus because it's built-in :smile: 

If maintainers use Scalastyle on internal projects then you probably have some opinions about its config settings, so probably better for you to pick them than me.

Let me know if there's an actionable step for me on this branch at this point.

**Comment by terryhorner** [comment]
Sound good.

**Pull request merged**
